### ISSUE TITLE
[BUG] The `test.py` fails to finish in the `moleculardynamics` stage.

### ISSUE THREAD

**Issue by shishaochen** [fenggo/I-ReaxFF#1]
I am developing a ReaXFF and your toolkit seems a pretty candidate :)

However, I checked out commit `913950c9bd011252cfb9aaee819d08fd65cb5cbb` from this repository and directly run:
```bash
python3 -u test.py
```

After several steps of geometry optimization, an error occured when running simulation with ASE.
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    moleculardynamics()
  File "/root/I-ReaxFF/md.py", line 36, in moleculardynamics
    nn=False)
  File "/root/I-ReaxFF/irff/md/irmd.py", line 109, in __init__
    self.atoms.calc.calculate(atoms=self.atoms)
  File "/root/I-ReaxFF/irff/irff.py", line 897, in calculate
    E = self.get_total_energy(cell,rcell,self.positions)
  File "/root/I-ReaxFF/irff/irff.py", line 842, in get_total_energy
    self.get_ebond(cell,rcell,positions)
  File "/root/I-ReaxFF/irff/irff.py", line 452, in get_ebond
    self.ebond = - self.P['Desi']*self.esi
AttributeError: 'IRFF' object has no attribute 'esi'
```

It seems that the routine of ASE simulation when `nn=False` has BUG.

Could you please fix it? Thx.

**Comment by fenggo** [comment]
the ffield.json file is missing.
